# Generated by Django 3.1 on 2021-05-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210508_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='orders',
            new_name='order',
        ),
    ]
